contact/urls.py
from django.urls import path

from . import views

app_name="contact"

urlpatterns = [
    path('', views.index, name='index'),
    path('contact_create_message', views.OnlineMessageCreateView.as_view(), name='OnlineMessageCreateView'),
    path('test_captcha', views.test_captcha, name='TestCaptcha'),
]

entsite/urls.py
from django.contrib import admin
from django.urls import include, path,re_path
from django.conf import settings
from django.conf.urls.static import static
from  django.views.static import serve
from .settings import MEDIA_ROOT

from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('', include('home.urls')),
    path('cases/', include('cases.urls')),
    path('contact/', include('contact.urls')),
    path('news/', include('news.urls')),
    path('about/', include('about.urls')),
    path('products/', include('products.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),
    re_path(r'^media/(?P<path>.*)$',serve,{'document_root': MEDIA_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

contact/models.py
from django.db import models
from common.models import MetaData, TimeStamped

from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import  RichTextUploadingField

# Create your models here.
class OnlineMessage(TimeStamped):

    name = models.CharField(_('name'), max_length=255, default=_(''))
    phone = models.CharField(_('phone'), max_length=255, default=_(''))

    message = models.TextField(_('message'), blank=True)
    
    def __str__(self):
        return self.message
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        
    class Meta:
        verbose_name = _('OnlineMessage')
        verbose_name_plural = _('在线留言')

contact/forms.py
from django import forms
from captcha.fields import CaptchaField

from .models import OnlineMessage

class OnlineMessageForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:  
        model = OnlineMessage
        fields = ['name','phone','message']

contact/views.py
import json
import re
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, View
from django.shortcuts import HttpResponse,get_object_or_404
from captcha.models import CaptchaStore
from captcha.helpers import captcha_image_url

from .models import OnlineMessage
from .forms import OnlineMessageForm
# Create your views here.
def index(request):
    context = {
        'msg': 'hello contact home',
    }
    return render(request, 'contact/index.html', context)

class OnlineMessageCreateView(CreateView):
    model = OnlineMessage
    fields = '__all__'
    def get(self, request, *args, **kwargs):
        print("enter!")
        #form = self.get_form()
        form = OnlineMessageForm()
        return render(request,'contact/onlinemessage_form.html',context={'form':form})
    def post(self, request, *args, **kwargs):
        res = dict(result=False)
        form = OnlineMessageForm(request.POST)#self.get_form()
        if form.is_valid():
            form.save()
            res['result'] = True
        else:
            print(form.errors)
            res['errors'] = form.errors.as_json()
        return HttpResponse(json.dumps(res), content_type='application/json')
def test_captcha(request):
    if request.method == "POST":
        form = OnlineMessageForm(request.POST)
        print(form)
        res = dict(result=False)
        if form.is_valid():
            form.save()
            res['result'] = True
            return render(request,'contact/test_captcha.html',context={'form':form})
        else:
            res['result'] = False
            res['errors'] = form.errors
            return HttpResponse(json.dumps(res), content_type='application/json')
            #print("has errors")
            #print(form.errors)
            #return render(request,'contact/test_captcha.html',context={'form':form})
    else:
        form = OnlineMessageForm()
        return render(request,'contact/test_captcha.html',context={'form':form})

contact/templates/contact/index.html
{% extends "base.html" %}
{% load static %}
{% block page-content %}
<ul>{{ msg }}</ul>
<form method="post" class="uniForm blueForms">
{% csrf_token %}
<button type="button" id="btnLeaveMessage"  class="btn btn-primary btn-sm" style="margin-bottom:5px;margin-right:8px;">在线留言</button>
</form>
{% endblock %}
{% block javascripts %}
    <script src="{% static 'layer351/layer.js' %}"></script>
	<script type="text/javascript">
	    $(function () {
		});
		$("#btnLeaveMessage").click(function () {
			layer.open({
            type: 2,
            title: '在线留言',
            shadeClose: false,
            maxmin: true,
            area: ['800px', '500px'],
            content: "{% url 'contact:OnlineMessageCreateView' %}",
            end: function () {
                //关闭时做的事情
                //oDataTable.ajax.reload();
            }
            });
        });
	</script>
{% endblock %}

contact/templates/contact/onlinemessage_form - 副本 (2).html
{% extends "base_layer.html" %}

{% block page-content %}
<form class="form-horizontal" id="addForm" method="post">
	{% csrf_token %}
	<div class="box-body">
		<fieldset>
			<div class="form-group has-feedback">
				<label class="col-sm-2 control-label">姓名</label>
				<div class="col-sm-8">
					<input class="form-control" name="name" type="text" />
				</div>
			</div>
			<div class="form-group has-feedback">
				<label class="col-sm-2 control-label">联系方式</label>
				<div class="col-sm-8">
					<input class="form-control" name="phone" type="text" />
				</div>
			</div>
			<div class="form-group has-feedback">
				<label class="col-sm-2 control-label">留言</label>
				<div class="col-sm-8">
					<input class="form-control" name="message" type="text" />
				</div>
			</div>
		</fieldset>
	</div>
	<div class="box-footer ">
		<div class="row span7 text-center ">
			<button type="button" id="btnCancel" class="btn btn-default margin-right ">重置</button>
			<button type="button" id="btnSave" class="btn btn-info margin-right ">在线留言</button>
		</div>
	</div>
</form>
{% endblock %}


{% block javascript %}
    <script type="text/javascript">
        $("#btnSave").click(function () {
            var data = $("#addForm").serialize();
            $.ajax({
                type: $("#addForm").attr('method'),
                url: "{% url 'contact:OnlineMessageCreateView' %}",
                data: data,
                cache: false,
                success: function (msg) {
                    if (msg.result) {
                        layer.alert('您已成功留言，我们会在近期与您联系，谢谢！', {icon:1,closeBtn:0,title:false}, function (index) {
                            parent.layer.closeAll(); //关闭所有弹窗
                        });
						//alert("success");
                    } else {
                        layer.alert('数据保存失败', {icon: 5,closeBtn:0,title:false});
                        //$('errorMessage').html(msg.message)
						//alert(msg.error);
                    }
                    return;
                }
            });
        });
        /*点取消刷新新页面*/
        $("#btnCancel").click(function () {
            window.location.reload();
        });
		
		//点击刷新验证码
        $(function () {
			$('.captcha').css({
				'cursor': 'pointer'
			});
			// ajax刷新
			$('.captcha').click(function () {
				console.log('click');
				$.get("{% url 'captcha-refresh' %}",
					function (result) {
						$('.captcha').attr('src', result['image_url']);
						$('#id_captcha_0').val(result['key'])
					});
			});
        })

    </script>

{% endblock %}

contact/templates/contact/onlinemessage_form - 副本.html
{% extends "base_layer.html" %}

{% block page-content %}

<form action="{% url 'contact:OnlineMessageCreateView' %}" method="post">
    {% csrf_token %}
    用户：{{ form.name }} <span>{{ form.name.errors.0 }}</span> <br>
    验证码：{{ form.captcha }} <span>{{ form.captcha.errors.0 }}</span><br>
    <input type="submit">
</form>

<form class="form-horizontal" id="addForm" method="post">
	{% csrf_token %}
	<div class="box-body">
		<fieldset>
			<div class="form-group has-feedback">
				<label class="col-sm-2 control-label">姓名</label>
				<div class="col-sm-8">
					<input class="form-control" name="name" type="text" />
				</div>
			</div>
			<div class="form-group has-feedback">
				<label class="col-sm-2 control-label">联系方式</label>
				<div class="col-sm-8">
					<input class="form-control" name="phone" type="text" />
				</div>
			</div>
			<div class="form-group has-feedback">
				<label class="col-sm-2 control-label">留言</label>
				<div class="col-sm-8">
					<input class="form-control" name="message" type="text" />
				</div>
			</div>
			<div class="form-group has-feedback">
				<label class="col-sm-2 control-label">验证码</label>
				<div class="col-sm-8">
					<img src="/captcha/image/ea65b35a692cbf47718b80186c8666b2a2354fc0/" alt="captcha" class="captcha" />
				</div>
			</div>
		</fieldset>
	</div>
	<div class="box-footer ">
		<div class="row span7 text-center ">
			<button type="button" id="btnCancel" class="btn btn-default margin-right ">重置</button>
			<button type="button" id="btnSave" class="btn btn-info margin-right ">在线留言</button>
		</div>
	</div>
</form>
{% endblock %}


{% block javascript %}
    <script type="text/javascript">
        $("#btnSave").click(function () {
            var data = $("#addForm").serialize();
            $.ajax({
                type: $("#addForm").attr('method'),
                url: "{% url 'contact:OnlineMessageCreateView' %}",
                data: data,
                cache: false,
                success: function (msg) {
                    if (msg.result) {
                        layer.alert('您已成功留言，我们会在近期与您联系，谢谢！', {icon:1,closeBtn:0,title:false}, function (index) {
                            parent.layer.closeAll(); //关闭所有弹窗
                        });
						//alert("success");
                    } else {
                        layer.alert('数据保存失败', {icon: 5,closeBtn:0,title:false});
                        //$('errorMessage').html(msg.message)
						//alert(msg.error);
                    }
                    return;
                }
            });
        });
        /*点取消刷新新页面*/
        $("#btnCancel").click(function () {
            window.location.reload();
        });
		
		//点击刷新验证码
        $(function () {
			$('.captcha').css({
				'cursor': 'pointer'
			});
			// ajax刷新
			$('.captcha').click(function () {
				console.log('click');
				$.get("{% url 'captcha-refresh' %}",
					function (result) {
						$('.captcha').attr('src', result['image_url']);
						$('#id_captcha_0').val(result['key'])
					});
			});
        })

    </script>

{% endblock %}

contact/templates/contact/onlinemessage_form.html
{% extends "base_layer.html" %}

{% block page-content %}
<form class="form-horizontal" id="addForm" method="post">
	{% csrf_token %}
	<div class="box-body">
		<fieldset>
			<div class="form-group has-feedback">
				<label class="col-sm-2 control-label">姓名</label>
				<div class="col-sm-8">
					<input class="form-control" name="name" type="text" />
				</div>
			</div>
			<div class="form-group has-feedback">
				<label class="col-sm-2 control-label">联系方式</label>
				<div class="col-sm-8">
					<input class="form-control" name="phone" type="text" />
				</div>
			</div>
			<div class="form-group has-feedback">
				<label class="col-sm-2 control-label">留言</label>
				<div class="col-sm-8">
					<input class="form-control" name="message" type="text" />
				</div>
			</div>
		</fieldset>
	</div>
	<div class="box-footer ">
		<div class="row span7 text-center ">
			<button type="button" id="btnCancel" class="btn btn-default margin-right ">重置</button>
			<button type="button" id="btnSave" class="btn btn-info margin-right ">在线留言</button>
		</div>
	</div>
</form>
{% endblock %}


{% block javascript %}
    <script type="text/javascript">
        $("#btnSave").click(function () {
            var data = $("#addForm").serialize();
            $.ajax({
                type: $("#addForm").attr('method'),
                url: "{% url 'contact:OnlineMessageCreateView' %}",
                data: data,
                cache: false,
                success: function (msg) {
                    if (msg.result) {
                        layer.alert('您已成功留言，我们会在近期与您联系，谢谢！', {icon:1,closeBtn:0,title:false}, function (index) {
                            parent.layer.closeAll(); //关闭所有弹窗
                        });
						//alert("success");
                    } else {
                        layer.alert('数据保存失败', {icon: 5,closeBtn:0,title:false});
                        //$('errorMessage').html(msg.message)
						//alert(msg.error);
                    }
                    return;
                }
            });
        });
        /*点取消刷新新页面*/
        $("#btnCancel").click(function () {
            window.location.reload();
        });

    </script>

{% endblock %}

contact/templates/contact/test_captcha - 副本.html
<!DOCTYPE html>
{% load static %}
<head>
    <meta charset="utf-8">
    <title>登录</title>
</head>
<body>
<div>{{ msg }}</div>
<form id="myForm" action="{% url 'contact:TestCaptcha' %}" method="post">
    {% csrf_token %}
    用户：{{ form.name }} <span>{{ form.name.errors.0 }}</span> <br>
	联系方式：{{ form.phone }} <span>{{ form.name.errors.0 }}</span> <br>
	留言：{{ form.message }} <span>{{ form.name.errors.0 }}</span> <br>
    验证码：{{ form.captcha }} <span>{{ form.captcha.errors.0 }}</span><br>
    <!-- <input type="submit"> -->
	<button type="submit" id="btnSave" class="btn btn-info margin-right ">在线留言</button>
</form>

<!-- <script src="https://cdn.bootcss.com/jquery/1.12.3/jquery.min.js"></script> -->
    <script src="{% static 'bootstrap337/js/jquery.min.js' %}"></script>
	<script src="{% static 'layer351/layer.js' %}"></script>
<script  type="text/javascript">

    $("#btnSave").on("click", function() {
	    //layer.msg('hello');
		<!-- layer.alert('您已成功留言，我们会在近期与您联系，谢谢！', {icon:1,closeBtn:0,title:false}, function (index) { -->
                            <!-- parent.layer.closeAll(); //关闭所有弹窗 -->
                        <!-- }); -->
		<!-- $.post("{% url 'contact:TestCaptcha' %}", $("#myForm").serialize()) -->
			<!-- .done(function(msg) {  -->
			    
			        <!-- if (msg.result) { -->
				        <!-- //window.alert(msg.result);   -->
                        
						<!-- //alert("success"); -->
                    <!-- } -->
			<!-- }); -->
			<!-- .fail(function() {  -->
			<!-- window.alert("Submission failed!");  -->
			<!-- }); -->
	        var data = $("#myForm").serialize();
            $.ajax({
                type: $("#myForm").attr('method'),
                url: "{% url 'contact:TestCaptcha' %}",
                data: data,
                cache: false,
                success: function (result) {
                    if (result.result) {
					    layer.alert('数据保存成功', {icon: 5,closeBtn:0,title:false});
					    <!-- window.alert(result.result); -->
                        <!-- layer.alert('您已成功留言，我们会在近期与您联系，谢谢！', {icon:1,closeBtn:0,title:false}, function (index) { -->
                            <!-- parent.layer.closeAll(); //关闭所有弹窗 -->
                        <!-- }); -->
						
						//alert("success");
                    } else {
                        layer.alert('数据保存失败', {icon: 5,closeBtn:0,title:false});
                        //$('errorMessage').html(msg.message)
						//alert(msg.error);
                    }
                    <!-- return; -->
                }
            });
    });
     //点击刷新验证码
    $(function () {
        $('.captcha').css({
            'cursor': 'pointer'
        });
        // ajax刷新
        $('.captcha').click(function () {
            console.log('click');
            $.get("{% url 'captcha-refresh' %}",
                function (result) {
                    $('.captcha').attr('src', result['image_url']);
                    $('#id_captcha_0').val(result['key'])
                });
        });
    })
</script>
</body>
</html>

contact/templates/contact/test_captcha.html
{% extends "base_layer.html" %}

{% block page-content %}
<form id="myForm" action="{% url 'contact:TestCaptcha' %}" method="post">
    {% csrf_token %}
    用户：{{ form.name }} <span>{{ form.name.errors.0 }}{{name_error}}</span> <br>
	联系方式：{{ form.phone }} <span>{{ form.phone.errors.0 }}</span> <br>
	留言：{{ form.message }} <span>{{ form.message.errors.0 }}</span> <br>
    验证码：{{ form.captcha }} <span>{{ form.captcha.errors.0 }}</span><br>
    <!-- <input type="submit"> -->
	<button type="submit" id="btnSave" class="btn btn-info margin-right ">在线留言</button>
</form>
{% endblock %}
{% block javascript %}
<script  type="text/javascript">

    $("#btnSave").on("click", function() {
	    <!-- e.preventDefault();  -->
		<!-- layer.msg('hello'); -->
		<!-- layer.alert('您已成功留言，我们会在近期与您联系，谢谢！', {icon:1,closeBtn:0,title:false}, function (index) { -->
                            <!-- parent.layer.closeAll(); //关闭所有弹窗 -->
                        <!-- }); -->
		<!-- $.post("{% url 'contact:TestCaptcha' %}", $("#myForm").serialize()) -->
			<!-- .done(function(msg) {  -->
			    
			        <!-- if (msg.result) { -->
				        <!-- //window.alert(msg.result);   -->
                        
						<!-- //alert("success"); -->
                    <!-- } -->
			<!-- }); -->
			<!-- .fail(function() {  -->
			<!-- window.alert("Submission failed!");  -->
			<!-- }); -->
	        var data = $("#myForm").serialize();
            r = $.ajax({
                type: $("#myForm").attr('method'),
                url: "{% url 'contact:TestCaptcha' %}",
                data: data,
                cache: false,
                success: function (result) {
			      if (result.result) {
				        alert("success");
				        <!-- window.location = window.close(); -->
                        layer.alert('数据保存成功', {icon: 5,closeBtn:0,title:false});
					    <!-- window.alert(result.result); -->
                        <!-- layer.alert('您已成功留言，我们会在近期与您联系，谢谢！', {icon:1,closeBtn:0,title:false}, function (index) { -->
                            <!-- parent.layer.closeAll(); //关闭所有弹窗 -->
                        <!-- }); -->
						
						//alert("success");
                    } else {
					    //alert(result.errors)
                        //layer.alert('数据保存失败', {icon: 5,closeBtn:0,title:false});
                        //$('errorMessage').html(msg.message)
						//alert(msg.error);
                    }
                    <!-- return; -->
                }
            });

					    
    });
     //点击刷新验证码
    $(function () {
        $('.captcha').css({
            'cursor': 'pointer'
        });
        // ajax刷新
        $('.captcha').click(function () {
            console.log('click');
            $.get("{% url 'captcha-refresh' %}",
                function (result) {
                    $('.captcha').attr('src', result['image_url']);
                    $('#id_captcha_0').val(result['key'])
                });
        });
    })
    </script>
{% endblock %}